# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-09 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='I_Organization',
            new_name='Organization',
        ),
    ]
