# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgManager', '0002_auto_20180710_0102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='i_organization',
        ),
    ]
